# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-03 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tr_NO', models.IntegerField(verbose_name='TR Number')),
                ('FromTeam', models.CharField(default='FromTeam', max_length=200)),
                ('ToTeam', models.CharField(default='ToTeam', max_length=200)),
                ('Prior_Int', models.IntegerField(verbose_name='Priority')),
                ('Pub_date', models.DateTimeField(verbose_name=' date published ')),
                ('owner', models.CharField(default='Not assigned', max_length=200)),
                ('comments', models.CharField(default='Comments', max_length=200)),
            ],
        ),
    ]
